// Production custom server: HTTP (SvelteKit) + WebSocket on the same port
import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';

// @ts-expect-error — generated by vite build
import { handler } from './build/handler.js';

const clients = new Set<WebSocket>();
let currentMetrics = { cadence: 0, resistance: 0 };

const httpServer = createServer(handler);
const wss = new WebSocketServer({ server: httpServer });

wss.on('connection', (ws) => {
	clients.add(ws);
	ws.send(JSON.stringify(currentMetrics));

	ws.on('message', (raw) => {
		try {
			const data = JSON.parse(raw.toString()) as Partial<typeof currentMetrics>;
			if ('cadence' in data && typeof data.cadence === 'number' && Number.isFinite(data.cadence)) {
				currentMetrics.cadence = Math.min(200, Math.max(0, data.cadence));
			}
			if ('resistance' in data && typeof data.resistance === 'number' && Number.isFinite(data.resistance)) {
				currentMetrics.resistance = Math.min(100, Math.max(0, data.resistance));
			}
			const msg = JSON.stringify(currentMetrics);
			for (const client of clients) {
				if (client.readyState === WebSocket.OPEN) {
					client.send(msg);
				}
			}
		} catch {
			// Ignore malformed messages
		}
	});

	ws.on('close', () => clients.delete(ws));
	ws.on('error', (err) => console.error('[WS] Client error:', err));
});

wss.on('error', (err) => console.error('[WS] Server error:', err));

const PORT = process.env.PORT ?? 3000;
httpServer.listen(PORT, () => {
	console.log(`PelotOWN running on http://localhost:${PORT}`);
});
